language: objective-c
osx_image: xcode7.3

before_install:
  - export GOROOT=/Users/travis/go
  - export GOPATH=/Users/travis
  - export OLD_DIR=$PWD
  - export NEW_DIR=/Users/travis/src/github.com/go-vu/cocoa
  - export PATH=$GOROOT/bin:$PATH

  - mkdir -p $NEW_DIR
  - curl -o /tmp/go.tar.gz https://storage.googleapis.com/golang/go1.6.2.darwin-amd64.tar.gz
  - (cd `dirname $GOROOT` && tar -xzf /tmp/go.tar.gz)
  - cd $NEW_DIR
  - mv $OLD_DIR cocoa
  - cd cocoa

  - go version

install:
  - go get -v -t .
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls

script:
  - go test -v -race -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out
