language: objective-c
osx_image: xcode7.3

before_install:
  - export GOROOT=/Users/travis/go
  - export GOPATH=/Users/travis
  - export PATH=$GOROOT/bin:$PATH
  - export REPO=github.com/go-vu/cocoa

  - curl -o /tmp/go.tar.gz https://storage.googleapis.com/golang/go1.6.2.darwin-amd64.tar.gz
  - (cd `dirname $GOROOT` && tar -xzf /tmp/go.tar.gz)
  - go version

  - cd $GOPATH/src
  - git clone --depth=50 --branch=master https://$REPO.git $REPO
  - cd $REPO
  - git checkout -qf $TRAVIS_COMMIT

install:
  - go get -v -t ./...
  - go get github.com/mattn/goveralls
  - go install github.com/mattn/goveralls

script:
  - go test -v -race -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out

notifications:
  email: false
